### ISSUE TITLE
Support for npm link

### ISSUE THREAD

**Issue by 4tron** [SamVerschueren/vscode-yo#31]
This is primarily for development purposes. Setting `npm link` to a local working directory allows for local development . Would be nice to be able to do something like `yo link c:/foo/foobar/fooprojectdir` and then when you go `yo` again the local yeoman project would be available.

**Comment by SamVerschueren** [comment]
That would be a feature for [yeoman](https://github.com/yeoman). This is only a UI wrapper for Visual Studio Code which uses the `yeoman` apis in the background.

What happens if you `npm link` your generator locally? My best guess is that it should pop up when running `yo` in the terminal? If that is the case, but it's not popping up in VS Code, try restarting the Code editor. If it's still not popping up, issue might be related with https://github.com/SamVerschueren/vscode-yo/issues/25

**Comment by 4tron** [comment]
When i link it in the terminal it doesn't show up , restarted now to check , didn't work. When i yo in terminal it doesn't show up either so it is an issue for yoeman in general . cheers

**Comment by 4tron** [comment]
Woops .. I had to have the name of the folder prefixed with `generator-` my bad
