### ISSUE TITLE
Cannot see npm install progress

### ISSUE THREAD

**Issue by chakkaradeep** [SamVerschueren/vscode-yo#52]
When I use within VS Code, the extension works but it does not show the npm install progress that happens. Is this a known issue? I tested this with multiple generators and got the same.

Thanks!

**Comment by SamVerschueren** [comment]
You should see a spinner in the bottom left corner.

**Comment by chakkaradeep** [comment]
I meant textual output like how you would get in a console/terminal with the npm progress bar.

**Comment by SamVerschueren** [comment]
I will have to check. But the issue with the npm progress bar is that it uses ANSI escape codes to update the progress. The output channels in VS Code don't support these so I think it won't look nice if I'm able to forward to output to the channel. Not sure about this though because I forward everything from `console.log` to that screen...
